### ISSUE TITLE
Apickli - Using output of first test as input to second test

### ISSUE THREAD

**Issue by Pari22** [apickli/apickli#107]
Hi,
I want to use output of first test as input to second test. Is it possible to create definitions, functions to achieve the same in apickli.js

Thanks.

**Comment by seymen** [comment]
It is possible (as it is just a node.js module, you can define and use global variables, etc) - but not recommended. See #92. We will also be removing unnecessary global variables and related gherkin statements from apickli code to discourage this in the future (for v3). Obviously if you insist on doing that, you can define such global variables in your own step definitions, etc.
