### ISSUE TITLE
Extra pair of braces for step definition in gherkin file

### ISSUE THREAD

**Issue by rohan-m** [apickli/apickli#109]
Regex matching results in callback == value and thus actual callback not defined.
needs replacement of  (((?!of type).*)) with ((?!of type).*) 

https://github.com/apickli/apickli/blob/58a347d4cc62046149ace65dd90d763866f69014/source/apickli/apickli-gherkin.js#L194-L199

**Comment by seymen** [comment]
@rohan-m - there are various tests in httpbin.feature and they all seem to be passing at the moment with the additional paran.

I've also put a `console.log(callback);` inside that function and I seem to be getting the callback function correctly.

Please check your setup one more time (cucumber, node versions, etc).
