### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by nothingp** [apickli/apickli#110]
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.relative (path.js:1226:5)
    at getDefinitionLineAndUri (node_modules/cucumber/lib/support_code_library_builder/define_helpers.js:144:28)

node -v v7.3.0

can u change the library of path.js ?

or update to node 8 ?

**Comment by seymen** [comment]
Are you using gulp with gulp-cucumber?

**Comment by seantdg** [comment]
@nothingp please provide more info on how to reproduce this. I am unable to recreate this issue.

**Comment by sidd-harth** [comment]
Hi, I am also getting the same here. i am running them in CentOS7. I am using latest versions of apickli & cucumber.
cucumber-js feature/api.feature gives the error,
TypeError: Path must be a string. Received undefined

When I run in Win10, it runs fine.

**Comment by seymen** [comment]
We are currently running `cucumber-js` command in [Travis](https://travis-ci.org/apickli/apickli) and it is working fine. Please review the setup there.
