### ISSUE TITLE
Request options to be cleared when request is sent

### ISSUE THREAD

**Issue by rohan-m** [apickli/apickli#121]
When making multiple request calls in a single scenario, previous request options are retained and not cleared.

**Comment by rohan-m** [comment]
We can clear all request options post response in the sendRequest function.
But if it defies the usage in scenario we can have a function to clear all the request options.

**Comment by seymen** [comment]
Look at creating a new instance of Apickli in order to setup a new connection. I know this is not ideal at the moment and I am working on an alternative to this at the moment.
