### ISSUE TITLE
Error: Error: getaddrinfo ENOTFOUND httpbin.orghttps httpbin.orghttps:80

### ISSUE THREAD

**Issue by PankajNalawade** [apickli/apickli#131]
I am running below scenario
Scenario: Setting headers in GET request
		 Given I set Content-Type header to application-json
   	 	 When I GET https://api.github.com/users/marktyers/orgs
         Then response code should be 200

below is the code in apickli-gherkin.js
module.exports = require('apickli/apickli-gherkin');

And below is the code in hooks.js

var {After, AfterAll, Before, BeforeAll} = require('cucumber');
const apickli = require('apickli');

Before({tags: "@api"}, function () {
    this.apickli = new apickli.Apickli('http', 'httpbin.org');
    this.apickli.addRequestHeader('Cache-Control', 'no-cache');
});

After running I am getting below error.
1) Scenario: Setting headers in GET request # features/api.feature:4
   ✔ Before # node_modules/apickli/apickli-gherkin.js:30
   ✔ Before # features/support/hooks.js:7
   ✔ Given I set Content-Type header to application-json # node_modules/apickli/apickli-gherkin.js:40
   ✖ When I GET https://api.github.com/users/marktyers/orgs # node_modules/apickli/apickli-gherkin.js:85
       Error: Error: getaddrinfo ENOTFOUND httpbin.orghttps httpbin.orghttps:80

**Comment by seymen** [comment]
Hi @PankajNalawade 

The idea is to define the scheme (http/https), and the domain name in `Before` handler and then specify resources only in the feature files.

What is the domain name of the target system you are trying to access? Is it httpbin.org or api.github.com? Whichever it is, define it in `Before` handler in hooks.js.

See apickli test scenarios if you want examples.

**Comment by PankajNalawade** [comment]
Hi Seymen thanks for your response and could you please let me know, what is the case if we have more than one domain name.
like
1) google.com
2)yahoo.com
