### ISSUE TITLE
Cucumber 4 won´t stop process

### ISSUE THREAD

**Issue by zazoomauro** [apickli/apickli#140]
With cucumber 4 the command process is not being stopped properly after all features. Same code with cucumber 3 works like a charm

**Comment by seymen** [comment]
Just run a new build in travis but can't see this: https://travis-ci.org/apickli/apickli/builds/399281114. Travis is running with 4.2.1.

Do you have any other info to reproduce?

**Comment by zazoomauro** [comment]
I´m running my tests using npm script in this way:

```
"test:integration": "npm run build && pm2 stop app.json --env test && pm2 start app.json --env test && npm run cucumber && pm2 stop app.json --env test",
"cucumber": "NODE_ENV=test babel-node node_modules/.bin/cucumber-js",
```

**Comment by zazoomauro** [comment]
@seymen any update on this?

**Comment by zazoomauro** [comment]
@seymen same problem for cucumber version 5

**Comment by seymen** [comment]
We are running cucumber 4 in our CI (travis - https://travis-ci.org/apickli/apickli) and it is executing and passing fine. I've just sent a PR for cucumber 5 support (just package.json update was sufficient) and it also executed fine in travis. Please check your environment and compare with how Travis is running it.
