### ISSUE TITLE
BDD changes not happen

### ISSUE THREAD

**Issue by rajeevchaturvedi2007** [apickli/apickli#143]
Hi ,
       I am using Apickli-gherkin for testing REST API in Apigee Platform.
When I checked installed version of the Node JS and NPM in my local laptop command prompt, I got below -
D:\WorkspaceNew\ProjectName>node -v
  **v6.9.1**
 D:\WorkspaceNew\ProjectName>npm -v 
**6.1.0**
 D:\WorkspaceNew\ProjectName>npm cucumber -v
  **6.1.0**

My package.json is :
----------------------
{
  "name": "Probes-tests",
  "version": "1.0.0",
  "devDependencies": {
    "apickli": "^1.0.0",
    "cucumber": "^0.5.3",
    "apigee-access": "1.3.0"
  },
  "dependencies": {
    "https": "^1.0.0"
  }
}
I run "npm install" from <my project/tests> folder and it will create and populate the node_modules folder.

Now, when I execute the command - from Project Directory  :
mvn test -Ptest -Dusername=userName-Dpassword=password

It execute the Scenario in the feature file but when I make changes for testing , it is always "Build Success". Attached here - screen shot. 
I think it is not executing the test cases in feature file, just read the feature file. What ever I make changes, it is always PASSED
PLease see the screen shot for more clarity.
Any one, please help to resolve where I am wrong?

Thanks 
Raj

**Comment by rajeevchaturvedi2007** [comment]
![apickli_issue](https://user-images.githubusercontent.com/24586381/42572664-78561fbc-8509-11e8-8736-0ea2818850aa.png)

**Comment by rajeevchaturvedi2007** [comment]
I have define the function in Apickli-gherkin.js in step_defination but still , it is saying - "You can implement step definitions for undefined steps with these snippets"

And some time saying - when adding a function - "
TypeError: this.apickli.addBodyParameters is not a function"
Any one know about it?

**Comment by seymen** [comment]
Your problem seems to be related to your maven configuration rather than apickli itself. Make sure that you are running cucumber properly, pointing to the correct feature files. See the travis output for how we are running cucumber for apickli: https://travis-ci.org/apickli/apickli
