### ISSUE TITLE
regExpObject.test(evalValue) fails

### ISSUE THREAD

**Issue by mrj04** [apickli/apickli#150]
✖ And response body path $.[0].message should be Resource Id [4625] does not exist # test/step_definitions/unify-steps.js:276
       Error: stepContext:
       testOutput:
         success:  false
         expected: Resource Id [4625] does not exist
         actual:   Resource Id [4625] does not exist
         response:
           statusCode: 400
           headers:
             content-type:                application/json
             content-length:              215
             connection:                  close
           

Even though the expected and actual are same the test case fails

**Comment by seymen** [comment]
Hi @mrj04 

The assertion is done against a regex, i.e. in `should be (.*)` the expression there is a regex.
So try `Resource Id \[4625\] does not exist` as [] denotes a range in regex.

**Comment by mrj04** [comment]
thanks @seymen ,
It worked with your suggestion.
