### ISSUE TITLE
Undefined. Implement with the Options snippet

### ISSUE THREAD

**Issue by Nanditab** [apickli/apickli#151]
I have written the following BDD test
>   Scenario: Return CORS headers for OPTIONS method
    When I request OPTIONS /v4
    Then response code should be 200
    And response header Access-Control-Allow-Credentials should be true
    And response header Access-Control-Allow-Methods should be GET, POST, PUT, DELETE, OPTIONS
    And response header Access-Control-Max-Age should be 86400
    And response header Content-Length should be 0
> 
However I get error 
`? When I request OPTIONS /v4
   Undefined. Implement with the following snippet:
          When('I request OPTIONS \/v{int}', function (int, callback) {

           // Write code here that turns the phrase above into concrete actions

           callback(null, 'pending');

         });
`
I have the following dependency set up
  "devDependencies": {
    "apickli": "latest",
    "cucumber": "^3.2.1",
    "cucumber-pretty": "^1.4.0"
}

Any pointer as what could be missing?

**Comment by seymen** [comment]
The correct statement is `I request OPTIONS for /v4`

**Comment by Nanditab** [comment]
Thanks!
