### ISSUE TITLE
Gulp test - Query regarding reports?

### ISSUE THREAD

**Issue by sidd-harth** [apickli/apickli#158]
Hi guys, I am following the Readme doc, using Gulp Integration to test the sample tests. I am able to run the tests, but I am not sure about how to generate the reports. I want to reports in JSON format.

After running tests I don't see any reports being generated, other than seeing errors on the console.

I saw the Gulpfile.js and see that the reports can be generated in JSON and HTML, but not sure how to generate and how to view them on the local machine.

Any help is appreciated.
@seymen

**Comment by seymen** [comment]
This is the implementation in Gulpfile.js: https://github.com/apickli/apickli/commit/0233fa958984ab1973c66b275c92d47a8fd2d72a
