### ISSUE TITLE
Handle nullish values passed from Cucumber Example Tables

### ISSUE THREAD

**Issue by sgkiokas** [apickli/apickli#184]
Raising [this](https://github.com/cucumber/cucumber-js/issues/1850) issue against `cucumber-js` which has been accepted as an enhancement, the suggestion from one of the contributors was for `apickli` [to handle nullish values](https://github.com/cucumber/cucumber-js/issues/1850#issuecomment-986003613).

Would it be something that can be considered here you reckon?

Thanks a lot in advance for your input!

**Comment by seymen** [comment]
Hi @sgkiokas 

Just to see the problem myself, I've implemented the following scenario:

```
  Scenario: should handle nullish values in request headers
    Given I set headers to
      | name     | value |
      | Endpoint |       |
    When I GET /get
    Then response body path $.headers.Endpoint should be ^$
```
And this seems to pass. I have a feeling that I am missing something. Could you share a Scenario that fails on your side please?

**Comment by sgkiokas** [comment]
Hi @seymen,

I suspect you kept the same versions of the dependencies, right? In my case, I'm using Examples Tables and not Data Tables, so I am not sure if there is a change in the implementation over there. For example:

```
Given I set Content-Type header to application/json
    And I set X-APIKEY header to <apikey>
    And I set Authorization header to Bearer <token>

Examples:
| apikey                  | token    |
| invalid-apikey          |          |
```

**Comment by seymen** [comment]
I have been able to reproduce this. This only seems to happen with Examples tables for which we had no tests on. PR is submitted.

**Comment by sgkiokas** [comment]
That was super fast! Thanks @seymen!

**Comment by seymen** [comment]
@sauliuz @laughingbiscuit - quick look at this? Otherwise I will just merge in next week.

**Comment by seymen** [comment]
v3.0.2 released to fix this
