### ISSUE TITLE
Error with gzip

### ISSUE THREAD

**Issue by Hyuden** [apickli/apickli#186]
hi guys i have a problem with apickli, when me make a report . The problem is rare characters with gzip.. im modified the apickli.js for gzip. the error persist.
https://stackoverflow.com/questions/70021552/problem-in-response-in-atomatization-with-gherking

**Comment by seymen** [comment]
Hi @Hyuden 

In your `Before` function, just add:
```
  this.apickli.httpRequestOptions = {
    gzip: true,
  };
```

**Comment by Hyuden** [comment]
Hi @seymen Your refer to Apickli.js? what line in specific?

**Comment by seymen** [comment]
No, not apickli.js. It is a file in your project (not in apickli) so I don't know what you called it. In the README, it is referred to as `init.js`. It has a function called `Before`. Could you search your project for a function called `Before` as per my original comment?

**Comment by Hyuden** [comment]
Yes, i modified before from init.js:
![image](https://user-images.githubusercontent.com/10159116/145078716-3501c5c4-9867-46f1-ac58-50e661931542.png)

**Comment by seymen** [comment]
I've added a test to https://github.com/apickli/apickli/pull/187 to show you how it is done. Please see the changes introduced in that PR and repeat in your implementation. Otherwise, modify that gzip scenario to demonstrate failure.

**Comment by Hyuden** [comment]
Hi i make the new proyect with your version i have one proble, the test cases doesnot iniciate.
![image](https://user-images.githubusercontent.com/10159116/145640083-93f5fd8c-8c33-4237-a571-735403c22d9e.png)

**Comment by seymen** [comment]
I don't know what that means, but in the PR https://github.com/apickli/apickli/pull/187, you can see that the tests are passing. I will close this for now, as you have an example of how it is working. I will merge this sometime this week.

**Comment by Hyuden** [comment]
Ok
