### ISSUE TITLE
ignoring input and appending output to 'nohup.out'

### ISSUE THREAD

**Issue by Hyuden** [apickli/apickli#188]
Hi wherever using command npm test in new version of apickli figure the next message with hours.

![image](https://user-images.githubusercontent.com/10159116/145824176-fcc58f66-270c-4788-98b1-ebd04ce060de.png)

a need help.

**Comment by Hyuden** [comment]
a need help :(

**Comment by seymen** [comment]
Sorry @Hyuden, I really don't know what it is that you are reporting. It doesn't seem to be related to apickli as all our local and CI builds work fine are passing at the moment. Try to run the node and npm commands separately if it helps, but we won't be able to provide any more help than this at this point. 

I will close this issue for now, but feel free to open it back if you believe it is something apickli related that needs to be fixed.
