### ISSUE TITLE
 Error: XPath parse error

### ISSUE THREAD

**Issue by Carllos166** [apickli/apickli#200]
`    Then response body path $.codigoLoja should be 1717
`
erro: 
![image](https://github.com/user-attachments/assets/b63d9960-be61-452e-9414-60db4c9f522c)

my postman response body:
   {
    "codigoLoja": 1717,
    "codigoTest": 249966,   
}

**Comment by adrian-ciobanu-icis** [comment]
I have the same issue. XPath parsing is not working anymore. Is this project still maintained in any way ?

**Comment by seymen** [comment]
Could you please try with v3.0.3? I've upgraded a number of packages to see if those created any regressions. All tests seem to be passing - see https://github.com/apickli/apickli/actions/runs/10819988204/job/30019118511

**Comment by adrian-ciobanu-icis** [comment]
It seems to work fine with v3.0.3 on my side. Thank you! :)

**Comment by adrian-ciobanu-icis** [comment]
Should you create a new release for v3.0.3 ? I don't see it in https://github.com/apickli/apickli/releases
