### ISSUE TITLE
Add an option to print out the actual response value which is being asserted

### ISSUE THREAD

**Issue by sauliuz** [apickli/apickli#28]
There should be optional flag to console log the actual response body / heaers / response code in addition to performing assertions

**Comment by oseymen-apigee** [comment]
I am in favour of giving additional information when scenario has failed (you asked to "foo", I get "bar"). But for success cases what you asked is that we get anyway. 

We definitely need to improve what we are printing out in the error cases but is it valuable to print out all that for success cases?

**Comment by sauliuz** [comment]
lets not enforce it but make it optional. config param?
