### ISSUE TITLE
Add an option to print out the request / response latency 

### ISSUE THREAD

**Issue by sauliuz** [apickli/apickli#29]
Need the option to print out the latency of API / how long it took to receive response after sending request.

**Comment by oseymen-apigee** [comment]
why do we need this? Wouldn't this make the results harder to read (it is hard as it is)? Also if you upgrade to the latest cucumber-js, you will get cumulative time summary at the end.

**Comment by sauliuz** [comment]
I guess this migh be optional. if someone want this for each scenario, they can print it out?

**Comment by oseymen-apigee** [comment]
We just need to careful to not go into performance testing realm with this. This request signals to me a potential misuse of the tool we are building. I have a feeling that we will then get PRs that incorporate apickli with some xyz performance testing tool.

**Comment by sauliuz** [comment]
agree
