### ISSUE TITLE
Add the ability to get a scenario variable

### ISSUE THREAD

**Issue by seantdg** [apickli/apickli#31]
Currently you can get and set global variables, however you can only set and assert scenario variables. It would be useful to have a function in apickli.js to get a scenario variables.

**Comment by sauliuz** [comment]
why dont to prefix a global variable name with scenario prefix?

**Comment by seantdg** [comment]
In the before hook, we typically re-instantiate apickli. In the apickli constructor we only reset this.scenarioVariables and not global variables (obviously :) ). As a work around, I am resetting the global variable too in the Before hook, but it would be good not to have to do this.

e.g. 
this.Before(function(scenario, callback) {
		this.apickli = new apickli.Apickli('https', 'something.apigee.net/v1');
		this.apickli.setGlobalVariable('{scenarioVariableToBeRead}', '');
		callback();
	});

**Comment by seymen** [comment]
@seantdg - does this affect your recent PR?

**Comment by seymen** [comment]
Would you like to use this instead?
```
this.apickli.scenarioVariables
```

**Comment by seantdg** [comment]
I can't think of any additional validation we would do on the scenario variable value before setting it, so I don't mind either way.

**Comment by oseymen-apigee** [comment]
what you really want is to encapsulate this type of access in a function, right?

**Comment by seymen** [comment]
what you really want is to encapsulate this type of access in a function, right?

**Comment by seantdg** [comment]
We already have Apickli.prototype.storeValueInScenarioScope(variableName, value)

so I am happy.
