### ISSUE TITLE
How do I add a proxy setting to apickli?

### ISSUE THREAD

**Issue by jaffamonkey** [apickli/apickli#47]
I have a pesky company proxy to navigate - how/where do I add this, so that apickli uses the proxy as tunnel to API endpoint?

**Comment by seymen** [comment]
Hi @jaffamonkey - have you tried setting HTTP_PROXY and/or HTTPS_PROXY environment variables (depending on whether you are doing http or https? See this: https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables

**Comment by jaffamonkey** [comment]
using export works OK :)

**Comment by seymen** [comment]
Perhaps this needs to go in documentation. I will reopen this to remind.
