### ISSUE TITLE
How to validate all assertions in response Body

### ISSUE THREAD

**Issue by animesh-gupta** [apickli/apickli#50]
Currently, if any of the assertion is failed then all the statements after that are skipped because of 'AND' clause.

We don't want to have duplicate test cases just for validations

**Comment by seymen** [comment]
@animesh-gupta - currently in cucumber, test execution stops when any of the assertions fail. This is not an apickli related behaviour - more cucumber.

I suggest you discuss this in those forums but this should help you to get started: http://stackoverflow.com/questions/15298521/continue-running-cucumber-steps-after-a-failure
