### ISSUE TITLE
How to validate a big response

### ISSUE THREAD

**Issue by animesh-gupta** [apickli/apickli#52]
Hi,

Could you help me in validating a very big response through Gherkins.

Eg: response with 20 and 30 lines and it will always come same for that request.

How can i do it or which scenario i can use it to write.

**Comment by seymen** [comment]
Hi @animesh-gupta - you haven't mentioned the response format but if it is json, you can easily do this using json schema support. Define a schema for the response. To assert against specific property values, use enum or pattern syntax.

For json schema validation with apickli, use this gherkin statement:
```
response body should be valid according to schema file (.*)
```
There are examples of this in tests.

**Comment by animesh-gupta** [comment]
Hi @seymen ,

If i create only a schema file and pass that file in the statement "response body should be valid according to schema file (.*)". Will this approach work?

**Comment by seymen** [comment]
Yes @animesh-gupta. All other statements are for validating a single property/element within the response. If response is too big, you don't want to assert them one by one. With schemas you also get the additional benefit of validating type or various other rules per property/element as well as values.
