### ISSUE TITLE
How to pass multiple data from excel sheet in our scenarios

### ISSUE THREAD

**Issue by animesh-gupta** [apickli/apickli#54]
Hi @seymen ,

I have a issue where i have multiple data in excel sheet and i want to use that multiple times for the same test case.

Eg:         Name                         Place
value       ABC                           ABC
value       XYZ                            XYZ

With Apache Jmeter i am able to pass everything from a file as comma separated and run the same test multiple times with different test data.

Could you please suggest how can this be done here.

**Comment by animesh-gupta** [comment]
Hi @seymen,

Could you please help us with the above issue.

**Comment by seymen** [comment]
Hi @animesh-gupta - check out scenario outlines feature of cucumber-js (https://github.com/cucumber/cucumber-js/blob/master/features/scenario_outlines.feature). apickli doesn't provide any additional functionality on top of this.

**Comment by preetham-salehundam** [comment]
@animesh-gupta  I have added a s
