### ISSUE TITLE
Not able to pass variables from one scenario to another

### ISSUE THREAD

**Issue by Carmot** [apickli/apickli#63]
Hello, I am developing an API proxy. I perform a login that returns two tokens I need in consecutive requests, so I store these values and use in the next scenario.
When I inject them they are blank for no apparenty reason.
I have been taking a look into the code and I think it is not possible to set a header to a value stored in the global scope, but I am not sure.
Please someone can help me?

Feature: Validate if WCS API Proxy provides expected functionality

Scenario: OK. Request to WCS Guest Login. Login
		Given I set Apikey header to nN3VsRWiinvhfWQrnP05G80jazTRVCh9
		When I POST to /xxxxxxxx-wcs-guest-login
		Then response code should be 201
		And response body should be valid json
		And response header Access-Control-Allow-Origin should exist
		And I store the value of body path $.WCToken as myWCToken in global scope
		Then I store the value of body path $.WCTrustedToken as myWCTrustedToken in global scope

Scenario: OK. Request to WCS Baskets. Add Items to Baskets
		Given I set headers to
		|name|value|
		|WCToken|`myWCToken`|
		|WCTrustedToken|`myWCTrustedToken`|
		|Apikey|nN3VsRWiinvhfWQrnP05G80jazTRVCh9|
		Given I set body to {"orderId":".","orderItem":[{"productId":"10706","quantity":"1"}],"x_calculateOrder":"0","x_inventoryValidation":"true"}
		When I POST to /xxxxxxxxxxxx-wcs-baskets/
		Then response code should be 200
		And response body should be valid json
		Then response header Access-Control-Allow-Origin should exist

**Comment by seymen** [comment]
@Carmot - can't see anything immediately wrong with this.

Here is my test which is looking for same things in response after setting values from response body path to global scope:

```
Feature: test

    Scenario: 1
        Given I set X-Input-1 header to value1
        And I set X-Input-2 header to value2
        When I POST to /post
        Then I store the value of body path $.headers.X-Input-1 as myvalue1 in global scope
        And I store the value of body path $.headers.X-Input-2 as myvalue2 in global scope

    Scenario: 2
        Given I set headers to
            | name    | value      |
            | X-Test1 | `myvalue1` |
            | X-Test2 | `myvalue2` |
        When I POST to /post
        Then response body path $.headers.X-Test1 should be value1
        And response body path $.headers.X-Test2 should be value2
```

One general suggestion - not specific to this: change last `Then` in each scenario to `And`.
