### ISSUE TITLE
apickli eats console log

### ISSUE THREAD

**Issue by bialesdaniel** [apickli/apickli#64]
Hi,

I found a bug in my code and I added a console log to debug it but since I'm using apickli the console log doesn't print out. Any suggestions?

**Comment by seymen** [comment]
@bialesdaniel - can you give more info? What do you think apickli is doing to prevent your console messages to print out?

**Comment by bialesdaniel** [comment]
I think this actually might have something to do with the test runner I wrote. Sorry for the confusion
