### ISSUE TITLE
Check an object exists in a response path

### ISSUE THREAD

**Issue by bialesdaniel** [apickli/apickli#69]
Hi,

I'm sure I'm just not understanding something but my test is failing and I don't know how to get the steps to check for the response value in the right way:

```
stepContext: 
  scenario: create user success
  step:     response body path environments should be production: true nonProduction: true
testOutput: 
  success:  false
  expected: production: true nonProduction: true
  actual: 
    production:    true
    nonProduction: true
  response: 
    statusCode: 201
    headers: 
      x-powered-by:   Express
      content-type:   application/json; charset=utf-8
      content-length: 87
      etag:           W/"57-NZwST3eL7b5VW6/DN41FOw"
      date:           Fri, 30 Sep 2016 01:11:14 GMT
      connection:     close
    body:       {"email":"test.user@email.com","environments":{"production":true,"nonProduction":true}}
```

**Comment by seymen** [comment]
@bialesdaniel - you haven't mentioned the actual step you have but if you are using jsonpath (which I think you are), then do 
```
response body path $.environments.production should be true
```

**Comment by bialesdaniel** [comment]
@seymen The step I'm trying to run is `response body path environments should be production: "true" nonProduction: "true"`

I'm not sure what you mean by using jsonpath. The response body I am getting is json. 

I tried the `response body path $.environments.production should be true` but it didn't seem to work. The test still failed.

**Comment by seymen** [comment]
@bialesdaniel - try this:

```
Then response body path $.environments.production should be true
And response body path $.environments.nonProduction should be true
```

**Comment by bialesdaniel** [comment]
yah I tried that and it didn't work

**Comment by seymen** [comment]
How is it any different than this:https://github.com/apickli/apickli/blob/master/source/test/features/httpbin.feature#L27

**Comment by bialesdaniel** [comment]
My issue is resolved. I wrote my own method for the multipart/form-data post but I wasn't correctly integrating it with the rest of the apickli code. I will try to add the multipart/form-data post code when I can and do a pull request

**Comment by zazoomauro** [comment]
@bialesdaniel can you share your custom step for multipart form data?
