### ISSUE TITLE
getPayloadItem is not a function

### ISSUE THREAD

**Issue by bialesdaniel** [apickli/apickli#72]
I'm trying to run some simple tests and I get this error 

```
TypeError: node_modules/apickli/apickli-gherkin.js:9 event.getPayloadItem is not a function
    at Object.handleBeforeScenario (/Users/n0235626/Documents/API_Management/amplifier---role-sync/node_modules/apickli/apickli-gherkin.js:10:30)
```

I was using cucumber v2.0.0-rc.1 It looks like the event object that you pass in has changed in the new version of cucumber. I downgraded to cucumber 1.3.0 and the tests passed again.

**Comment by bialesdaniel** [comment]
If I comment out these two function my tests pass.
```
    this.registerHandler('BeforeScenario', function (event, callback) {
        var scenario = event.getPayloadItem('scenario');
        stepContext.scenario = scenario.getName();
        callback();
    });
    
    this.registerHandler('BeforeStep', function(event, callback) {
        var step = event.getPayloadItem('step');
        stepContext.step = step.getName();
        callback();
    });
```

**Comment by seymen** [comment]
@bialesdaniel - apickli doesn't interfere how you are using cucumber.js event handlers. Please refer to cucumber.js documentation on how to use such handlers. This is nothing to do with apickli.

(https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/event_handlers.md)

**Comment by wwwbeck** [comment]
what version of cucumber are you using?
"
cucumber event handlers attached via registerHandler are now passed the associated object instead of an event
getPayloadItem will be removed in the next major release
"

**Comment by bialesdaniel** [comment]
Yes I'm using 2.0.0 so I fixed this by downgrading to 1.3.0. I just thought it might be helpful to bring this up as a potential issue as more people start using 2.0.0

**Comment by wwwbeck** [comment]
I see. Put in a pull request with the fix :)

**Comment by bialesdaniel** [comment]
Ok. is the goal of those two steps just to assign the scenario and step name to stepContext.scenario and stepContext.step? Thats what it looks like to me. right?
