### ISSUE TITLE
Don't know how to make "When I POST" to work.

### ISSUE THREAD

**Issue by dsgill** [apickli/apickli#75]
I need to POST to a server at a specific URL. I try to use the statement
       When I POST to http://configapi.idc1.boon.com:3001/servConfig/v1/subscribers
but cucumber.js only says that it's undefined. I'm using apickli-gherkin so it looks like it should work. How does my URL need to be specified?

**Comment by seymen** [comment]
Hi @dsgill this is because of backwards incompatible changes in cucumber.js 2 (,hence the version upgrade) which I believe you are using. A fix is on the way very shortly.

**Comment by seymen** [comment]
@dsgill - this should be fixed with 1.7.3.
