### ISSUE TITLE
Version Update to Cucumber v2

### ISSUE THREAD

**Issue by michaelshaffer37** [apickli/apickli#89]
The javascript [Cucumber](https://github.com/cucumber/cucumber-js/tree/v2.3.1) package updated to [v2](https://github.com/cucumber/cucumber-js/tree/v2.3.1) and this package is no longer compatible with the new approach to defining [step definitions](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/step_definitions.md).  There is likely other potential updates needed as well.

Just wanted to bring this to the attention of the maintainers.  I am thinking I may take a quick stab at this this weekend and see what I can do but ultimately this will likely need a major version bump and I'm not sure how you want to handle it.

Thanks for the great package.

**Comment by seymen** [comment]
Hi @michaelshaffer37 - thanks!

Yes we are aware of the underlying changes to cucumber. Possible workaround is to use ^1 for the cucumber version in package.json but we must upgrade apickli to be compatible.

There is also 1 other PR (that changes the openapi wording in gherkin statements) which will also go in apickli V2. I don't think I will be able to work on this for the next 3 weeks but after I return from holidays this will be at the top of my list.

This backwards incompatible work will also give us an opportunity to get community feedback to see what other things people want to be changed in apickli. So comments welcome!

**Comment by seymen** [comment]
#106 is coming to fix this.

**Comment by seymen** [comment]
fixed by 58a347d4cc62046149ace65dd90d763866f69014
