### ISSUE TITLE
Swagger validation passed when it should fail

### ISSUE THREAD

**Issue by andrii-denysov** [apickli/apickli#90]
Verification doesn't work properly, tests that should failed passed. When pass incorrect definition for getting failure 400 response we've got passed instead (so this step (`response body should be valid according to swagger definition (.*) in file (.*)`) works not as expected).

[Feature and Spec.zip](https://github.com/apickli/apickli/files/1187800/Feature.and.Spec.zip)

Attached swagger spec in *.json format and test in *.feature file.

**Comment by illegal** [comment]
Hi @andrii-denysov , please provide example JSON of invalid response body which was mistakenly identified as valid by swagger validator.
Thanks

**Comment by andrii-denysov** [comment]
Hi @illegal, here it is:
 `{
    "code": "card.number.invalid",
    "message": "Please enter the correct card number"
}`

**Comment by illegal** [comment]
@andrii-denysov 
According to the spec, there can be an error response (HTTP status 400) which should contain two optional properties "code" and "message". That means that the JSON example you provided is absolutely valid according to your spec.

**Comment by andrii-denysov** [comment]
@illegal 
Yep, but if we swap definitions in feature it'll pass too, but shouldn't.

**Comment by illegal** [comment]
Hi @andrii-denysov 
So you are trying to validate JSON
```
{
  "code": "card.number.invalid",
  "message": "Please enter the correct card number"
}
```
with the following spec
```
    "CardType": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "Visa",
            "Partnership Card",
            "American Express",
            "Solo",
            "Maestro",
            "MasterCard",
            "Delta",
            "Electron",
            "Business Account"
          ]
        },
        "cardNumberLength": {
          "type": "number"
        },
        "securityCodeLength": {
          "type": "number"
        }
      },
      "example": {
        "type": "Visa",
        "cardNumberLength": 19,
        "securityCodeLength": 3
      }
    }
```
and I believe the thing is that `CardType` definition does not mark any *required* properties, which is why validation does not fail.

**Comment by seymen** [comment]
@andrii-denysov 

All apickli is doing is to use the `swagger-tools` module's validate function, see https://github.com/apickli/apickli/blob/master/source/apickli/apickli.js#L328. If there are any problems with catching and reporting any errors on apickli end, let us know. Otherwise you might get better support from `swagger-tools` project.
